#!/usr/bin/env ruby

SCRIPT_PATH = File.readlink($0)
IMAGE_PATH = File.join(File.dirname(SCRIPT_PATH), 'images')
FAILURE = 1
SUCCESS = 0

def growl(outcome, msg)
  image = outcome == FAILURE ? "#{IMAGE_PATH}/scalalogo-red.png" : "#{IMAGE_PATH}/scalalogo-green.png"
  growl_cmd = "growlnotify --image #{image} --name 'sbt' -t 'sbt test' -m '#{msg}'"
  `#{growl_cmd}`
end

IO.popen("sbt \"~ test\"") do |io|
  while(line = io.gets)

    # ScalaTest 2.0
    if line.match /All tests passed/
      puts line
      growl SUCCESS, 'All tests passed.'
    elsif line.match /TEST FAILED/
      puts line
      growl FAILURE, 'Tests failed.'

    # Specs / Specs2
    elsif line.match /Passed\:/
      puts line
      growl SUCCESS, 'All tests passed.'

    # General stuff (eg compilation)
    elsif line.match /Compilation failed/
      puts line
      growl FAILURE, 'Compilation failed! Tests were not run.'

    # Everything else just print out
    else
      puts line
    end
  end
end
